name: ExploitFixer
main: dev._2lstudios.exploitfixer.ExploitFixer
version: 1.6.4
author: 2LS
api: "1.13"
api-version: "1.13"
softdepend: [HamsterAPI]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
